# Generated by Django 6.0.2 on 2026-04-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='region',
            field=models.CharField(default='Unknown', help_text='Wilaya', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='suspicious_movement',
            field=models.BooleanField(default=False),
        ),
    ]
