# Generated by Django 6.0.2 on 2026-04-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_animal_is_verified_animal_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='location_name',
            field=models.CharField(blank=True, help_text='Detailed address (City, Wilaya)', max_length=255, null=True),
        ),
    ]
