# Generated by Django 6.0.2 on 2026-04-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pickup_address_order_transporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'مدفوع - جاهز للنقل'), ('processing', 'قيد التحضير'), ('shipped', 'تم الشحن'), ('delivered', 'تم الاستلام'), ('cancelled', 'ملغى')], default='paid', max_length=20),
        ),
    ]
