# Generated by Django 6.0.3 on 2026-03-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='official_prices/')),
                ('date_set', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_set'],
            },
        ),
    ]
