# Generated by Django 6.0.2 on 2026-03-29 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('official_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='products.officialprice')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
