# Generated by Django 6.0.3 on 2026-03-28 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_officialprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officialprice',
            name='date_set',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
