# Generated by Django 6.0.2 on 2026-04-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_officialprice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialprice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
