# Generated by Django 6.0.2 on 2026-05-03 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_buyerstock'),
        ('users', '0004_user_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerstock',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_stock_sourced', to='users.farmer'),
        ),
    ]
